# Generated by Django 4.2.4 on 2023-11-19 22:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Perfume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('concentration', models.CharField(choices=[('Eau Fraiche', 'Eau Fraiche'), ('Eau de Cologne', 'Eau de Cologne'), ('Eau de Toilette', 'Eau de Toilette'), ('Eau de Parfum', 'Eau de Parfum'), ('Parfum', 'Parfum')], max_length=64)),
                ('year', models.SmallIntegerField(null=True)),
                ('base_notes', models.ManyToManyField(related_name='perfumes_base_note', to='scent_app.note')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scent_app.brand')),
                ('category', models.ManyToManyField(to='scent_app.category')),
                ('middle_notes', models.ManyToManyField(related_name='perfumes_middle_note', to='scent_app.note')),
            ],
        ),
        migrations.CreateModel(
            name='Perfumer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='UserPerfume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.SmallIntegerField(null=True)),
                ('status', models.CharField(max_length=255, null=True)),
                ('to_exchange', models.BooleanField(default=False)),
                ('perfume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scent_app.perfume')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SwapOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('offering_perfume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offering_perfume', to='scent_app.userperfume')),
                ('requested_perfume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_perfume', to='scent_app.perfume')),
            ],
        ),
        migrations.AddField(
            model_name='perfume',
            name='perfumer',
            field=models.ManyToManyField(to='scent_app.perfumer'),
        ),
        migrations.AddField(
            model_name='perfume',
            name='top_notes',
            field=models.ManyToManyField(related_name='perfumes_top_note', to='scent_app.note'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='perfume',
            unique_together={('name', 'brand', 'concentration')},
        ),
    ]
