# Generated by Django 4.2.4 on 2023-08-13 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Perfume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concentration', models.CharField(choices=[('Eau Fraiche', 'Eau Fraiche'), ('Eau de Cologne', 'Eau de Cologne'), ('Eau de Toilette', 'Eau de Toilette'), ('Eau de Parfum', 'Eau de Parfum'), ('Parfum', 'Parfum')], max_length=32)),
                ('year', models.SmallIntegerField(null=True)),
                ('base_notes', models.ManyToManyField(related_name='perfumes_base_note', to='scent_app.note')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scent_app.brand')),
                ('category', models.ManyToManyField(to='scent_app.category')),
                ('middle_notes', models.ManyToManyField(related_name='perfumes_middle_note', to='scent_app.note')),
            ],
        ),
        migrations.CreateModel(
            name='Perfumer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64, unique=True)),
                ('email', models.CharField(max_length=64, unique=True)),
                ('password', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='UserPerfume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.SmallIntegerField()),
                ('status', models.CharField(max_length=255)),
                ('to_exchange', models.BooleanField(default=False)),
                ('perfume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scent_app.perfume')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scent_app.user')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='perfumes',
            field=models.ManyToManyField(through='scent_app.UserPerfume', to='scent_app.perfume'),
        ),
        migrations.CreateModel(
            name='SwapOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_accepted', models.BooleanField(default=False)),
                ('offering_perfume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offering_perfume', to='scent_app.userperfume')),
                ('requested_perfume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_perfume', to='scent_app.userperfume')),
            ],
        ),
        migrations.AddField(
            model_name='perfume',
            name='perfumer',
            field=models.ManyToManyField(to='scent_app.perfumer'),
        ),
        migrations.AddField(
            model_name='perfume',
            name='top_notes',
            field=models.ManyToManyField(related_name='perfumes_top_note', to='scent_app.note'),
        ),
    ]
