# Generated by Django 4.2.4 on 2023-08-13 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scent_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfume',
            name='name',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
