# Generated by Django 4.2.4 on 2023-08-15 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scent_app', '0004_remove_swapoffer_message_alter_userperfume_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfume',
            name='category',
            field=models.ManyToManyField(to='scent_app.category'),
        ),
    ]
