# Generated by Django 4.2.4 on 2023-08-15 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scent_app', '0005_perfume_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfume',
            name='concentration',
            field=models.CharField(choices=[('Eau Fraiche', 'Eau Fraiche'), ('Eau de Cologne', 'Eau de Cologne'), ('Eau de Toilette', 'Eau de Toilette'), ('Eau de Parfum', 'Eau de Parfum'), ('Parfum', 'Parfum')], max_length=64),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
