# Generated by Django 4.2.4 on 2023-08-21 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scent_app', '0006_alter_perfume_concentration_alter_perfume_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='swapoffer',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
