# Generated by Django 4.2.4 on 2023-08-27 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scent_app', '0007_swapoffer_is_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='swapoffer',
            name='requested_perfume',
        ),
        migrations.AddField(
            model_name='swapoffer',
            name='requested_perfumes',
            field=models.ManyToManyField(related_name='requested_perfume', to='scent_app.perfume'),
        ),
    ]
