# Generated by Django 4.2.4 on 2023-08-28 16:34

from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('scent_app', '0009_remove_swapoffer_requested_perfumes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swapoffer',
            name='requested_perfume',
            field=models.ForeignKey(on_delete=django.db.models.fields.Empty, related_name='requested_perfume', to='scent_app.perfume'),
        ),
    ]
