# Generated by Django 4.2.4 on 2023-08-28 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scent_app', '0010_alter_swapoffer_requested_perfume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfume',
            name='concentration',
            field=models.CharField(choices=[('Eau Fraiche', 'Eau Fraiche'), ('Eau de Cologne', 'Eau de Cologne'), ('EdT', 'Eau de Toilette'), ('Eau de Parfum', 'Eau de Parfum'), ('Parfum', 'Parfum')], max_length=64),
        ),
    ]
