# Generated by Django 4.2.4 on 2023-08-28 19:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scent_app', '0012_alter_perfume_concentration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swapoffer',
            name='requested_perfume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_perfume', to='scent_app.perfume'),
        ),
        migrations.AlterField(
            model_name='userperfume',
            name='status',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userperfume',
            name='volume',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
                ('title', models.ForeignKey(on_delete=models.SET('Deleted offer'), to='scent_app.swapoffer')),
            ],
        ),
    ]
