# Generated by Django 4.2.4 on 2023-09-03 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scent_app', '0013_alter_swapoffer_requested_perfume_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='swapoffer',
            name='is_accepted',
        ),
        migrations.AlterField(
            model_name='message',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
