# Generated by Django 4.2.4 on 2023-09-06 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scent_app', '0014_remove_swapoffer_is_accepted_alter_message_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='title',
        ),
    ]
